import { Member, Relationship, MemberWithRelations } from "./types"

export const mockMembers: Member[] = [
  {
    id: "1",
    slug: "suparto-1920",
    fullName: "Suparto Wibowo",
    nickname: "Mbah Parto",
    gender: "male",
    birthDate: "1920-03-15",
    birthPlace: "Yogyakarta",
    deathDate: "2005-11-20",
    deathPlace: "Yogyakarta",
    isAlive: false,
    religion: "Islam",
    occupation: "Petani",
    bio: "Leluhur pertama keluarga besar Wibowo. Merupakan tokoh yang disegani di desa, dikenal bijaksana dan pekerja keras. Mendirikan tanah keluarga yang kini ditinggali keturunannya.",
    photoUrl: null,
    address: "Jl. Kenanga No. 12, Yogyakarta",
    generation: 1,
    createdAt: "2024-01-01T00:00:00Z",
    updatedAt: "2024-01-01T00:00:00Z",
    deletedAt: null,
  },
  {
    id: "2",
    slug: "sri-wahyuni-1925",
    fullName: "Sri Wahyuni",
    nickname: "Mbah Sri",
    gender: "female",
    birthDate: "1925-08-22",
    birthPlace: "Klaten",
    deathDate: "2010-02-14",
    deathPlace: "Yogyakarta",
    isAlive: false,
    religion: "Islam",
    occupation: "Ibu Rumah Tangga",
    bio: "Istri Suparto Wibowo. Ahli memasak masakan tradisional Jawa yang resepnya diturunkan ke anak-anak dan cucunya.",
    photoUrl: null,
    address: "Jl. Kenanga No. 12, Yogyakarta",
    generation: 1,
    createdAt: "2024-01-01T00:00:00Z",
    updatedAt: "2024-01-01T00:00:00Z",
    deletedAt: null,
  },
  {
    id: "3",
    slug: "budi-santoso-1950",
    fullName: "Budi Santoso",
    nickname: "Pak Budi",
    gender: "male",
    birthDate: "1950-07-01",
    birthPlace: "Yogyakarta",
    deathDate: null,
    deathPlace: null,
    isAlive: true,
    religion: "Islam",
    occupation: "PNS Pensiunan",
    bio: "Anak pertama Suparto dan Sri. Bekerja sebagai Pegawai Negeri Sipil selama 30 tahun.",
    photoUrl: null,
    address: null,
    generation: 2,
    createdAt: "2024-01-01T00:00:00Z",
    updatedAt: "2024-01-01T00:00:00Z",
    deletedAt: null,
  },
  {
    id: "4",
    slug: "dewi-sartika-1955",
    fullName: "Dewi Sartika",
    nickname: "Bu Dewi",
    gender: "female",
    birthDate: "1955-11-12",
    birthPlace: "Magelang",
    deathDate: null,
    deathPlace: null,
    isAlive: true,
    religion: "Islam",
    occupation: "Guru",
    bio: "Guru SD yang mengabdi selama 35 tahun. Istri Budi Santoso.",
    photoUrl: null,
    address: null,
    generation: 2,
    createdAt: "2024-01-01T00:00:00Z",
    updatedAt: "2024-01-01T00:00:00Z",
    deletedAt: null,
  },
  {
    id: "5",
    slug: "edi-prasetyo-1978",
    fullName: "Edi Prasetyo",
    nickname: "Mas Edi",
    gender: "male",
    birthDate: "1978-04-20",
    birthPlace: "Yogyakarta",
    deathDate: null,
    deathPlace: null,
    isAlive: true,
    religion: "Islam",
    occupation: "Software Engineer",
    bio: "Anak pertama Budi dan Dewi. Bekerja di perusahaan teknologi.",
    photoUrl: null,
    address: null,
    generation: 3,
    createdAt: "2024-01-01T00:00:00Z",
    updatedAt: "2024-01-01T00:00:00Z",
    deletedAt: null,
  },
  {
    id: "6",
    slug: "rina-melati-1980",
    fullName: "Rina Melati",
    nickname: "Mbak Rina",
    gender: "female",
    birthDate: "1980-09-05",
    birthPlace: "Yogyakarta",
    deathDate: null,
    deathPlace: null,
    isAlive: true,
    religion: "Islam",
    occupation: "Dokter",
    bio: "Anak kedua Budi dan Dewi. Dokter spesialis anak di RSUD.",
    photoUrl: null,
    address: null,
    generation: 3,
    createdAt: "2024-01-01T00:00:00Z",
    updatedAt: "2024-01-01T00:00:00Z",
    deletedAt: null,
  },
  {
    id: "7",
    slug: "ratna-kusuma-1960",
    fullName: "Ratna Kusuma",
    nickname: "Bu Ratna",
    gender: "female",
    birthDate: "1960-02-28",
    birthPlace: "Yogyakarta",
    deathDate: null,
    deathPlace: null,
    isAlive: true,
    religion: "Islam",
    occupation: "Pengusaha",
    bio: "Anak kedua Suparto dan Sri. Pemilik usaha catering.",
    photoUrl: null,
    address: null,
    generation: 2,
    createdAt: "2024-01-01T00:00:00Z",
    updatedAt: "2024-01-01T00:00:00Z",
    deletedAt: null,
  },
  {
    id: "8",
    slug: "agung-pratama-1985",
    fullName: "Agung Pratama",
    nickname: "Agung",
    gender: "male",
    birthDate: "1985-12-25",
    birthPlace: "Yogyakarta",
    deathDate: null,
    deathPlace: null,
    isAlive: true,
    religion: "Islam",
    occupation: "Arsitek",
    bio: "Anak Ratna Kusuma. Arsitek yang menangani proyek di berbagai kota.",
    photoUrl: null,
    address: null,
    generation: 3,
    createdAt: "2024-01-01T00:00:00Z",
    updatedAt: "2024-01-01T00:00:00Z",
    deletedAt: null,
  },
  {
    id: "9",
    slug: "ayu-lestari-2020",
    fullName: "Ayu Lestari",
    nickname: "Ayu",
    gender: "female",
    birthDate: "2020-01-10",
    birthPlace: "Jakarta",
    deathDate: null,
    deathPlace: null,
    isAlive: true,
    religion: "Islam",
    occupation: null,
    bio: "Anak Edi Prasetyo. Generasi ke-4.",
    photoUrl: null,
    address: null,
    generation: 4,
    createdAt: "2024-01-01T00:00:00Z",
    updatedAt: "2024-01-01T00:00:00Z",
    deletedAt: null,
  },
  {
    id: "10",
    slug: "dimas-pratama-2022",
    fullName: "Dimas Pratama",
    nickname: "Dimas",
    gender: "male",
    birthDate: "2022-05-15",
    birthPlace: "Jakarta",
    deathDate: null,
    deathPlace: null,
    isAlive: true,
    religion: "Islam",
    occupation: null,
    bio: "Anak Edi Prasetyo. Generasi ke-4.",
    photoUrl: null,
    address: null,
    generation: 4,
    createdAt: "2024-01-01T00:00:00Z",
    updatedAt: "2024-01-01T00:00:00Z",
    deletedAt: null,
  },
]

export const mockRelationships: Relationship[] = [
  { id: "r1", memberId: "3", relatedMemberId: "1", relationType: "parent", marriageDate: null, createdAt: "2024-01-01T00:00:00Z" },
  { id: "r2", memberId: "3", relatedMemberId: "2", relationType: "parent", marriageDate: null, createdAt: "2024-01-01T00:00:00Z" },
  { id: "r3", memberId: "7", relatedMemberId: "1", relationType: "parent", marriageDate: null, createdAt: "2024-01-01T00:00:00Z" },
  { id: "r4", memberId: "7", relatedMemberId: "2", relationType: "parent", marriageDate: null, createdAt: "2024-01-01T00:00:00Z" },
  { id: "r5", memberId: "3", relatedMemberId: "4", relationType: "spouse", marriageDate: "1975-06-15", createdAt: "2024-01-01T00:00:00Z" },
  { id: "r6", memberId: "4", relatedMemberId: "3", relationType: "spouse", marriageDate: "1975-06-15", createdAt: "2024-01-01T00:00:00Z" },
  { id: "r7", memberId: "5", relatedMemberId: "3", relationType: "parent", marriageDate: null, createdAt: "2024-01-01T00:00:00Z" },
  { id: "r8", memberId: "5", relatedMemberId: "4", relationType: "parent", marriageDate: null, createdAt: "2024-01-01T00:00:00Z" },
  { id: "r9", memberId: "6", relatedMemberId: "3", relationType: "parent", marriageDate: null, createdAt: "2024-01-01T00:00:00Z" },
  { id: "r10", memberId: "6", relatedMemberId: "4", relationType: "parent", marriageDate: null, createdAt: "2024-01-01T00:00:00Z" },
  { id: "r11", memberId: "8", relatedMemberId: "7", relationType: "parent", marriageDate: null, createdAt: "2024-01-01T00:00:00Z" },
  { id: "r12", memberId: "9", relatedMemberId: "5", relationType: "parent", marriageDate: null, createdAt: "2024-01-01T00:00:00Z" },
  { id: "r13", memberId: "10", relatedMemberId: "5", relationType: "parent", marriageDate: null, createdAt: "2024-01-01T00:00:00Z" },
  { id: "r14", memberId: "1", relatedMemberId: "2", relationType: "spouse", marriageDate: "1945-08-01", createdAt: "2024-01-01T00:00:00Z" },
  { id: "r15", memberId: "2", relatedMemberId: "1", relationType: "spouse", marriageDate: "1945-08-01", createdAt: "2024-01-01T00:00:00Z" },
]

export function getMemberWithRelations(memberId: string): MemberWithRelations | null {
  const member = mockMembers.find((m) => m.id === memberId)
  if (!member) return null

  const relations = mockRelationships.filter((r) => r.memberId === memberId)

  const parentIds = relations.filter((r) => r.relationType === "parent").map((r) => r.relatedMemberId)
  const spouseIds = relations.filter((r) => r.relationType === "spouse").map((r) => r.relatedMemberId)

  const childRelations = mockRelationships.filter(
    (r) => r.relatedMemberId === memberId && r.relationType === "parent"
  )
  const childIds = childRelations.map((r) => r.memberId)

  return {
    ...member,
    parents: mockMembers.filter((m) => parentIds.includes(m.id)),
    spouses: mockMembers.filter((m) => spouseIds.includes(m.id)),
    children: mockMembers.filter((m) => childIds.includes(m.id)),
  }
}

export function getMemberBySlug(slug: string): MemberWithRelations | null {
  const member = mockMembers.find((m) => m.slug === slug)
  if (!member) return null
  return getMemberWithRelations(member.id)
}

export function getRootMembers(): Member[] {
  const allMemberIds = mockMembers.map((m) => m.id)
  const children = new Set(
    mockRelationships
      .filter((r) => r.relationType === "parent")
      .map((r) => r.memberId)
  )
  return mockMembers.filter((m) => !children.has(m.id) && !m.deletedAt)
}
